CREATE TABLE `fctdevice` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `dimDate` int(11) NOT NULL,
  `dimHour` int(11) NOT NULL,
  `dimProfile` int(11) NOT NULL,
  `dimGeo` int(11) NOT NULL,
  `dimPlatform` int(11) NOT NULL,
  `dimSystem` int(11) NOT NULL,
  `dimNetwork` int(11) NOT NULL,
  `dimVisitor` int(11) NOT NULL,
  `Visits` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `fk_fctDevice_dimDate_idx` (`dimDate`),
  KEY `fk_fctDevice_dimHour_idx` (`dimHour`),
  KEY `fk_fctDevice_dimProfile_idx` (`dimProfile`),
  KEY `fk_fctDevice_dimGeo_idx` (`dimGeo`),
  KEY `fk_fctDevice_dimPlatform_idx` (`dimPlatform`),
  KEY `fk_fctDevice_dimSystem_idx` (`dimSystem`),
  KEY `fk_fctDevice_dim_idx` (`dimNetwork`),
  KEY `fk_fctDevice_dimVisitor_idx` (`dimVisitor`),
  CONSTRAINT `fk_fctDevice_dimDate` FOREIGN KEY (`dimDate`) REFERENCES `dimdate` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctDevice_dimGeo` FOREIGN KEY (`dimGeo`) REFERENCES `dimgeo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctDevice_dimHour` FOREIGN KEY (`dimHour`) REFERENCES `dimhour` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctDevice_dimNetwork` FOREIGN KEY (`dimNetwork`) REFERENCES `dimnetwork` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctDevice_dimPlatform` FOREIGN KEY (`dimPlatform`) REFERENCES `dimplatform` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctDevice_dimProfile` FOREIGN KEY (`dimProfile`) REFERENCES `dimprofile` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctDevice_dimSystem` FOREIGN KEY (`dimSystem`) REFERENCES `dimsystem` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctDevice_dimVisitor` FOREIGN KEY (`dimVisitor`) REFERENCES `dimvisitor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=199 DEFAULT CHARSET=latin1