CREATE TABLE `fctevent` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `dimDate` int(11) NOT NULL,
  `dimProfile` int(11) NOT NULL,
  `dimEvent` int(11) NOT NULL,
  `Visits` int(11) NOT NULL DEFAULT '0',
  `Visitors` int(11) NOT NULL DEFAULT '0',
  `NewVisits` int(11) NOT NULL DEFAULT '0',
  `Bounces` int(11) NOT NULL DEFAULT '0',
  `TimeOnSite` float NOT NULL DEFAULT '0',
  `GoalCompletionsAll` int(11) NOT NULL DEFAULT '0',
  `Entrances` int(11) NOT NULL DEFAULT '0',
  `Pageviews` int(11) NOT NULL DEFAULT '0',
  `TimeOnPage` float NOT NULL DEFAULT '0',
  `Exits` int(11) NOT NULL DEFAULT '0',
  `totalEvents` int(11) NOT NULL DEFAULT '0',
  `uniqueEvents` int(11) NOT NULL DEFAULT '0',
  `eventValue` int(11) NOT NULL DEFAULT '0',
  `visitsWithEvent` int(11) NOT NULL DEFAULT '0',
  `eventsPerVisitWithEvent` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `indx_dimEvent` (`dimDate`,`dimProfile`,`dimEvent`),
  KEY `fk_dimEvent_dimDate_idx` (`dimDate`),
  KEY `fk_dimEvent_dimProfile_idx` (`dimProfile`),
  KEY `fk_fctdimEvent_dimEvent_idx` (`dimEvent`),
  CONSTRAINT `fk_fctEvent_dimDate` FOREIGN KEY (`dimDate`) REFERENCES `dimdate` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctEvent_dimEvent` FOREIGN KEY (`dimEvent`) REFERENCES `dimevent` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctEvent_dimProfile` FOREIGN KEY (`dimProfile`) REFERENCES `dimprofile` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=194 DEFAULT CHARSET=latin1