CREATE TABLE `fctexitpagepath` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `dimDate` int(11) NOT NULL,
  `dimProfile` int(11) NOT NULL,
  `dimLandingPagePath` int(11) NOT NULL,
  `dimExitPagePath` int(11) NOT NULL,
  `dimVisitor` int(11) NOT NULL,
  `dimDaysSinceLastVisit` int(11) NOT NULL,
  `Visits` int(11) NOT NULL DEFAULT '0',
  `Visitors` int(11) NOT NULL DEFAULT '0',
  `NewVisits` int(11) NOT NULL DEFAULT '0',
  `Bounces` int(11) NOT NULL DEFAULT '0',
  `TimeOnSite` float NOT NULL DEFAULT '0',
  `OrganicSearches` int(11) NOT NULL DEFAULT '0',
  `GoalStartsAll` int(11) NOT NULL DEFAULT '0',
  `GoalCompletionsAll` int(11) NOT NULL DEFAULT '0',
  `GoalAbandonsAll` int(11) NOT NULL DEFAULT '0',
  `GoalValueAll` float NOT NULL DEFAULT '0',
  `Entrances` int(11) NOT NULL DEFAULT '0',
  `Pageviews` int(11) NOT NULL DEFAULT '0',
  `UniquePageviews` int(11) NOT NULL DEFAULT '0',
  `TimeOnPage` float NOT NULL DEFAULT '0',
  `Exits` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `indx_dimExitPagePath` (`dimDate`,`dimProfile`,`dimExitPagePath`,`dimLandingPagePath`,`dimVisitor`,`dimDaysSinceLastVisit`),
  KEY `fk_fctExitPagePath_dimDate_idx` (`dimDate`),
  KEY `fk_fctExitPagePath_dimDaysSinceLastVisit_idx` (`dimDaysSinceLastVisit`),
  KEY `fk_fctExitPagePath_dimProfile_idx` (`dimProfile`),
  KEY `fk_fctExitPagePath_dimVisitor_idx` (`dimVisitor`),
  KEY `fk_fctExitPagePath_dimLandingPagePath_idx` (`dimLandingPagePath`),
  KEY `fk_fctExitPagePath_dimExitPagePath_idx` (`dimExitPagePath`),
  CONSTRAINT `fk_fctExitPagePath_dimDate` FOREIGN KEY (`dimDate`) REFERENCES `dimdate` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctExitPagePath_dimDaysSinceLastVisit` FOREIGN KEY (`dimDaysSinceLastVisit`) REFERENCES `dimdaysince` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctExitPagePath_dimExitPagePath` FOREIGN KEY (`dimExitPagePath`) REFERENCES `dimpagepath` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctExitPagePath_dimLandingPagePath` FOREIGN KEY (`dimLandingPagePath`) REFERENCES `dimpagepath` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctExitPagePath_dimProfile` FOREIGN KEY (`dimProfile`) REFERENCES `dimprofile` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctExitPagePath_dimVisitor` FOREIGN KEY (`dimVisitor`) REFERENCES `dimvisitor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=291 DEFAULT CHARSET=latin1