CREATE TABLE `fctform` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `dimProfile` int(11) NOT NULL,
  `dimDate` int(11) NOT NULL,
  `dimVisitor` int(11) NOT NULL,
  `dimSession` int(11) NOT NULL,
  `dimPagePath` int(11) NOT NULL,
  `dimHostName` int(11) NOT NULL,
  `Visitors` int(11) NOT NULL DEFAULT '0',
  `NewVisits` int(11) NOT NULL DEFAULT '0',
  `Bounces` int(11) NOT NULL DEFAULT '0',
  `OrganicSearches` int(11) NOT NULL DEFAULT '0',
  `Entrances` int(11) NOT NULL DEFAULT '0',
  `Pageviews` int(11) NOT NULL DEFAULT '0',
  `UniquePageviews` int(11) NOT NULL DEFAULT '0',
  `TimeOnPage` float NOT NULL DEFAULT '0',
  `Exits` int(11) NOT NULL DEFAULT '0',
  `TimeOnSite` int(11) NOT NULL DEFAULT '0',
  `Visits` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `indx_fctForm` (`dimProfile`,`dimDate`,`dimVisitor`,`dimSession`,`dimPagePath`,`dimHostName`),
  KEY `fk_fctForm_dimDate_idx` (`dimDate`),
  KEY `fk_fctForm_dimVisitor_idx` (`dimVisitor`),
  KEY `fk_fctForm_dimSession_idx` (`dimSession`),
  KEY `fk_fctForm_dimHostName_idx` (`dimHostName`),
  KEY `fk_fctForm_dimPagePath_idx` (`dimPagePath`),
  KEY `fk_fctForm_dimProfile_idx` (`dimProfile`),
  CONSTRAINT `fk_fctForm_dimDate` FOREIGN KEY (`dimDate`) REFERENCES `dimdate` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctForm_dimHostName` FOREIGN KEY (`dimHostName`) REFERENCES `dimhostname` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctForm_dimPagePath` FOREIGN KEY (`dimPagePath`) REFERENCES `dimpagepath` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctForm_dimProfile` FOREIGN KEY (`dimProfile`) REFERENCES `dimprofile` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctForm_dimSession` FOREIGN KEY (`dimSession`) REFERENCES `dimsession` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctForm_dimVisitor` FOREIGN KEY (`dimVisitor`) REFERENCES `dimvisitor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1716 DEFAULT CHARSET=latin1