CREATE TABLE `fctvsdevice` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `dimDate` int(11) NOT NULL,
  `dimHour` int(11) NOT NULL,
  `dimProfile` int(11) NOT NULL,
  `dimGeo` int(11) NOT NULL,
  `dimPlatform` int(11) NOT NULL,
  `dimSystem` int(11) NOT NULL,
  `dimNetwork` int(11) NOT NULL,
  `dimVisitor` int(11) NOT NULL,
  `dimVanquisSession` int(11) NOT NULL,
  `Visits` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `fk_fctvsDevice_dimDate` (`dimDate`),
  KEY `fk_fctvsDevice_dimGeo` (`dimGeo`),
  KEY `fk_fctvsDevice_dimHour` (`dimHour`),
  KEY `fk_fctvsDevice_dimNetwork` (`dimNetwork`),
  KEY `fk_fctvsDevice_dimPlatform` (`dimPlatform`),
  KEY `fk_fctvsDevice_dimProfile` (`dimProfile`),
  KEY `fk_fctvsDevice_dimSystem` (`dimSystem`),
  KEY `fk_fctvsDevice_dimVisitor` (`dimVisitor`),
  KEY `fk_fctvsDevice_dimVanquisSession` (`dimVanquisSession`),
  CONSTRAINT `fk_fctvsDevice_dimDate` FOREIGN KEY (`dimDate`) REFERENCES `dimdate` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimGeo` FOREIGN KEY (`dimGeo`) REFERENCES `dimgeo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimHour` FOREIGN KEY (`dimHour`) REFERENCES `dimhour` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimNetwork` FOREIGN KEY (`dimNetwork`) REFERENCES `dimnetwork` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimPlatform` FOREIGN KEY (`dimPlatform`) REFERENCES `dimplatform` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimProfile` FOREIGN KEY (`dimProfile`) REFERENCES `dimprofile` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimSystem` FOREIGN KEY (`dimSystem`) REFERENCES `dimsystem` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimVisitor` FOREIGN KEY (`dimVisitor`) REFERENCES `dimvisitor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctvsDevice_dimVanquisSession` FOREIGN KEY (`dimVanquisSession`) REFERENCES `dimcustomvar` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=latin1