CREATE TABLE `fctvanquissession` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `dimDate` int(11) NOT NULL,
  `dimProfile` int(11) NOT NULL,
  `dimVanquisSession` int(11) NOT NULL,
  `Visits` int(11) NOT NULL DEFAULT '0',
  `Visitors` int(11) NOT NULL DEFAULT '0',
  `NewVisits` int(11) NOT NULL DEFAULT '0',
  `Bounces` int(11) NOT NULL DEFAULT '0',
  `TimeOnSite` float NOT NULL DEFAULT '0',
  `OrganicSearches` int(11) NOT NULL DEFAULT '0',
  `GoalStartsAll` int(11) NOT NULL DEFAULT '0',
  `GoalCompletionsAll` int(11) NOT NULL DEFAULT '0',
  `GoalAbandonsAll` int(11) NOT NULL DEFAULT '0',
  `GoalValueAll` float NOT NULL DEFAULT '0',
  `Entrances` int(11) NOT NULL DEFAULT '0',
  `Pageviews` int(11) NOT NULL DEFAULT '0',
  `UniquePageviews` int(11) NOT NULL DEFAULT '0',
  `TimeOnPage` float NOT NULL DEFAULT '0',
  `Exits` int(11) NOT NULL DEFAULT '0',
  `PageLoadTime` int(11) NOT NULL DEFAULT '0',
  `PageLoadSample` int(11) NOT NULL DEFAULT '0',
  `DomainLookupTime` int(11) NOT NULL DEFAULT '0',
  `PageDownloadTime` int(11) NOT NULL DEFAULT '0',
  `RedirectionTime` int(11) NOT NULL DEFAULT '0',
  `ServerConnectionTime` int(11) NOT NULL DEFAULT '0',
  `ServerResponseTime` int(11) NOT NULL DEFAULT '0',
  `SpeedMetricsSample` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `fk_fctVanquisSession_dimVanquisSession` (`dimVanquisSession`),
  KEY `fk_fctVanquisSession_dimDate` (`dimDate`),
  KEY `fk_fctVanquisSession_dimProfile` (`dimProfile`),
  CONSTRAINT `fk_fctVanquisSession_dimVanquisSession` FOREIGN KEY (`dimVanquisSession`) REFERENCES `dimcustomvar` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctVanquisSession_dimDate` FOREIGN KEY (`dimDate`) REFERENCES `dimdate` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_fctVanquisSession_dimProfile` FOREIGN KEY (`dimProfile`) REFERENCES `dimprofile` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1