<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 19:30:19.
 */
class googleResultsWrapperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var googleResultsWrapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new googleResultsWrapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers googleResultsWrapper::mergeResults
     * @todo   Implement testMergeResults().
     */
    public function testMergeResults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleResultsWrapper::globalAddDimension
     * @todo   Implement testGlobalAddDimension().
     */
    public function testGlobalAddDimension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleResultsWrapper::getRows
     * @todo   Implement testGetRows().
     */
    public function testGetRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleResultsWrapper::getColumnHeaders
     * @todo   Implement testGetColumnHeaders().
     */
    public function testGetColumnHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleResultsWrapper::getMetrics
     * @todo   Implement testGetMetrics().
     */
    public function testGetMetrics()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleResultsWrapper::getDimensions
     * @todo   Implement testGetDimensions().
     */
    public function testGetDimensions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleResultsWrapper::getFilter
     * @todo   Implement testGetFilter().
     */
    public function testGetFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
