<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 19:30:15.
 */
class googleHelperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var googleHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new googleHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers googleHelper::getFirstId
     * @todo   Implement testGetFirstId().
     */
    public function testGetFirstId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::getAllIDs
     * @todo   Implement testGetAllIDs().
     */
    public function testGetAllIDs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::getRows
     * @todo   Implement testGetRows().
     */
    public function testGetRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::resetCount
     * @todo   Implement testResetCount().
     */
    public function testResetCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::splitDims
     * @todo   Implement testSplitDims().
     */
    public function testSplitDims()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::splitMets
     * @todo   Implement testSplitMets().
     */
    public function testSplitMets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::getGAResults
     * @todo   Implement testGetGAResults().
     */
    public function testGetGAResults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::getMCFResults
     * @todo   Implement testGetMCFResults().
     */
    public function testGetMCFResults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::getFilter
     * @todo   Implement testGetFilter().
     */
    public function testGetFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::getMetrics
     * @todo   Implement testGetMetrics().
     */
    public function testGetMetrics()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers googleHelper::getDimensions
     * @todo   Implement testGetDimensions().
     */
    public function testGetDimensions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
