<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-22 at 19:30:16.
 */
class VanquisTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Vanquis
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Vanquis;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Vanquis::test
     * @todo   Implement testTest().
     */
    public function testTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::Date
     * @todo   Implement testDate().
     */
    public function testDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::getResults
     * @todo   Implement testGetResults().
     */
    public function testGetResults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::waterfall
     * @todo   Implement testWaterfall().
     */
    public function testWaterfall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::ProfileDates
     * @todo   Implement testProfileDates().
     */
    public function testProfileDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::LoanHistory
     * @todo   Implement testLoanHistory().
     */
    public function testLoanHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::Device
     * @todo   Implement testDevice().
     */
    public function testDevice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::adWords
     * @todo   Implement testAdWords().
     */
    public function testAdWords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::CashMax
     * @todo   Implement testCashMax().
     */
    public function testCashMax()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::getPageTracking
     * @todo   Implement testGetPageTracking().
     */
    public function testGetPageTracking()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::getvsDateToQuery141
     * @todo   Implement testGetvsDateToQuery141().
     */
    public function testGetvsDateToQuery141()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::getvsDateToQuery
     * @todo   Implement testGetvsDateToQuery().
     */
    public function testGetvsDateToQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::sessionData
     * @todo   Implement testSessionData().
     */
    public function testSessionData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::performance
     * @todo   Implement testPerformance().
     */
    public function testPerformance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::google
     * @todo   Implement testGoogle().
     */
    public function testGoogle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Vanquis::testMCF
     * @todo   Implement testTestMCF().
     */
    public function testTestMCF()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
